### ISSUE TITLE
Hope to add button width 

### ISSUE THREAD

**Issue by HinokiSu** [fect-org/fect#173]
# About `styles` 🛠️
Hey,  Is it possible to add `width` on the button.
I can now only change the button width as shown below： 

```html
<div class="search">
  <fe-button size="large" ghost>Search</fe-button>
</div>
```

```css
.search {
  button {
    min-width: 40px;
  }
}
```
